apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
  namespace: prod
  labels:
    app: devops-project
spec:
  replicas: 3 # High availability in prod
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: registry.gitlab.com/sergeshorace1986/devops-project:latest # replace with your image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: devops-project-config
            - secretRef:
                name: devops-project-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
            