apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
  namespace: prod              # ← prod
  labels:
    app: devops-project
    env: prod
spec:
  replicas: 2                  # ← 2 replicas for prod
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
      containers:
        - name: devops-project
          image: registry.gitlab.com/sergeshorace1986/devops-project:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: devops-project-config
            - secretRef:
                name: devops-project-secret
          resources:
            requests:
              cpu: "200m"      # ← higher than dev
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
