apiVersion: v1
kind: Secret
metadata:
  name: devops-project-secret
  namespace: prod
type: Opaque
stringData:
  DB_PASSWORD: "ZzLMlpvqDf86HU34Di8a7Q=="
  API_KEY: "55252efbbb2be63f6994ee55120da205514c1649"