# k8s/prod/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
  namespace: prod
  labels:
    app: devops-project
    env: prod
spec:
  selector:
    app: devops-project
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
